
Ìroot"_tf_keras_sequential*»{"name": "sequential", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": {"class_name": "__tuple__", "items": [null, null]}, "dtype": "int32", "sparse": false, "ragged": false, "name": "module_wrapper_input"}}, {"class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}, {"class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}, {"class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}, {"class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}, {"class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}]}, "shared_object_id": 1, "build_input_shape": {"class_name": "TensorShape", "items": [null, null]}, "is_graph_network": true, "save_spec": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 200]}, "float32", "module_wrapper_input"]}, "keras_version": "2.5.0", "backend": "tensorflow", "model_config": {"class_name": "Sequential"}, "training_config": {"loss": "binary_crossentropy", "metrics": [[{"class_name": "MeanMetricWrapper", "config": {"name": "accuracy", "dtype": "float32", "fn": "binary_accuracy"}, "shared_object_id": 2}, {"class_name": "MeanMetricWrapper", "config": {"name": "recall", "dtype": "float32", "fn": {"class_name": "Recall", "config": {"name": "recall", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}, "__passive_serialization__": true, "shared_object_id": 3}}, "shared_object_id": 4}, {"class_name": "MeanMetricWrapper", "config": {"name": "false_negatives", "dtype": "float32", "fn": {"class_name": "FalseNegatives", "config": {"name": "false_negatives", "dtype": "float32", "thresholds": null}, "__passive_serialization__": true, "shared_object_id": 5}}, "shared_object_id": 6}, {"class_name": "MeanMetricWrapper", "config": {"name": "precision", "dtype": "float32", "fn": {"class_name": "Precision", "config": {"name": "precision", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}, "__passive_serialization__": true, "shared_object_id": 7}}, "shared_object_id": 8}]], "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "learning_rate": 0.0010000000474974513, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
∫root.layer_with_weights-0"_tf_keras_layer*É{"name": "module_wrapper", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}2
Øroot.layer-1"_tf_keras_layer*Ö{"name": "module_wrapper_1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}2
ºroot.layer_with_weights-1"_tf_keras_layer*Ö{"name": "module_wrapper_2", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}2
Øroot.layer-3"_tf_keras_layer*Ö{"name": "module_wrapper_3", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}2
ºroot.layer_with_weights-2"_tf_keras_layer*Ö{"name": "module_wrapper_4", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "ModuleWrapper", "config": {"layer was saved without config": true}}2
∏droot.keras_api.metrics.0"_tf_keras_metric*Å{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 9}2
Êeroot.keras_api.metrics.1"_tf_keras_metric*Ø{"class_name": "MeanMetricWrapper", "name": "accuracy", "dtype": "float32", "config": {"name": "accuracy", "dtype": "float32", "fn": "binary_accuracy"}, "shared_object_id": 2}2
äfroot.keras_api.metrics.2"_tf_keras_metric*”{"class_name": "MeanMetricWrapper", "name": "recall", "dtype": "float32", "config": {"name": "recall", "dtype": "float32", "fn": {"class_name": "Recall", "config": {"name": "recall", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}, "__passive_serialization__": true, "shared_object_id": 3}}, "shared_object_id": 4}2
ågroot.keras_api.metrics.3"_tf_keras_metric*’{"class_name": "MeanMetricWrapper", "name": "false_negatives", "dtype": "float32", "config": {"name": "false_negatives", "dtype": "float32", "fn": {"class_name": "FalseNegatives", "config": {"name": "false_negatives", "dtype": "float32", "thresholds": null}, "__passive_serialization__": true, "shared_object_id": 5}}, "shared_object_id": 6}2
ñhroot.keras_api.metrics.4"_tf_keras_metric*ﬂ{"class_name": "MeanMetricWrapper", "name": "precision", "dtype": "float32", "config": {"name": "precision", "dtype": "float32", "fn": {"class_name": "Precision", "config": {"name": "precision", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}, "__passive_serialization__": true, "shared_object_id": 7}}, "shared_object_id": 8}2