# Generated by Django 3.1.7 on 2021-03-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('twitter', 'twitter'), ('reddit', 'reddit')], max_length=7)),
                ('output', models.FloatField(default=-1.0)),
            ],
        ),
    ]
