# Generated by Django 3.2.3 on 2021-05-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('content', models.TextField(unique=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('twitter', 'twitter'), ('reddit', 'reddit')], max_length=7)),
                ('output', models.IntegerField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High'), ('-1', 'Untested')], default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('low_si', models.TextField()),
                ('med_si', models.TextField()),
                ('high_si', models.TextField()),
                ('platform', models.CharField(choices=[('twitter', 'twitter'), ('reddit', 'reddit')], max_length=7)),
            ],
        ),
    ]
