# Generated by Django 3.2 on 2021-05-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sarcasm',
            field=models.BooleanField(default=False),
        ),
    ]
